# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from server import policy_pb2 as server_dot_policy__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in server/policy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolicyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerInfo = channel.unary_unary(
                '/rl100.remote.v1.PolicyService/GetServerInfo',
                request_serializer=server_dot_policy__pb2.ServerInfoRequest.SerializeToString,
                response_deserializer=server_dot_policy__pb2.ServerInfoResponse.FromString,
                _registered_method=True)
        self.Infer = channel.unary_unary(
                '/rl100.remote.v1.PolicyService/Infer',
                request_serializer=server_dot_policy__pb2.InferenceRequest.SerializeToString,
                response_deserializer=server_dot_policy__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.ResetEpisode = channel.unary_unary(
                '/rl100.remote.v1.PolicyService/ResetEpisode',
                request_serializer=server_dot_policy__pb2.ResetEpisodeRequest.SerializeToString,
                response_deserializer=server_dot_policy__pb2.ResetEpisodeResponse.FromString,
                _registered_method=True)


class PolicyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=server_dot_policy__pb2.ServerInfoRequest.FromString,
                    response_serializer=server_dot_policy__pb2.ServerInfoResponse.SerializeToString,
            ),
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=server_dot_policy__pb2.InferenceRequest.FromString,
                    response_serializer=server_dot_policy__pb2.InferenceResponse.SerializeToString,
            ),
            'ResetEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetEpisode,
                    request_deserializer=server_dot_policy__pb2.ResetEpisodeRequest.FromString,
                    response_serializer=server_dot_policy__pb2.ResetEpisodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl100.remote.v1.PolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl100.remote.v1.PolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl100.remote.v1.PolicyService/GetServerInfo',
            server_dot_policy__pb2.ServerInfoRequest.SerializeToString,
            server_dot_policy__pb2.ServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl100.remote.v1.PolicyService/Infer',
            server_dot_policy__pb2.InferenceRequest.SerializeToString,
            server_dot_policy__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl100.remote.v1.PolicyService/ResetEpisode',
            server_dot_policy__pb2.ResetEpisodeRequest.SerializeToString,
            server_dot_policy__pb2.ResetEpisodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
